apiVersion: v1
kind: Service
metadata:
  name: servicio-app-1
  labels:
    name: despliegue-app-1
    app: Despliegue-app-1
spec:
  type: NodePort
  selector:
    app: Despliegue-app-1
  ports:
    - protocol: TCP
      port: 3500
      nodePort: 30027


